# Hands-on Activity 8.1: Aggregating Data with Pandas

Install dependencies

In [1]:
import pandas as pd
import numpy as np

Import datasets

In [2]:
earthquakes_df = pd.read_csv('earthquakes.csv')
faang_df = pd.read_csv('faang.csv')

In [3]:
earthquakes_df

,mag,magType,time,place,tsunami,parsed_place
0,1.35,ml,1539475168010,"9km NE of Aguanga, CA",0,California
1,1.29,ml,1539475129610,"9km NE of Aguanga, CA",0,California
2,3.42,ml,1539475062610,"8km NE of Aguanga, CA",0,California
3,0.44,ml,1539474978070,"9km NE of Aguanga, CA",0,California
4,2.16,md,1539474716050,"10km NW of Avenal, CA",0,California
...,...,...,...,...,...,...
9327,0.62,md,1537230228060,"9km ENE of Mammoth Lakes, CA",0,California
9328,1.00,ml,1537230135130,"3km W of Julian, CA",0,California
9329,2.40,md,1537229908180,"35km NNE of Hatillo, Puerto Rico",0,Puerto Rico
9330,1.10,ml,1537229545350,"9km NE of Aguanga, CA",0,California
9331,0.66,ml,1537228864470,"9km NE of Aguanga, CA",0,California

In [4]:
faang_df

     ticker        date     open     high        low    close    volume
0        FB  2018-01-02   177.68   181.58   177.5500   181.42  18151903
1        FB  2018-01-03   181.88   184.78   181.3300   184.67  16886563
2        FB  2018-01-04   184.90   186.21   184.0996   184.33  13880896
3        FB  2018-01-05   185.59   186.90   184.9300   186.85  13574535
4        FB  2018-01-08   187.20   188.90   186.3300   188.28  17994726
...     ...         ...      ...      ...        ...      ...       ...
1250   GOOG  2018-12-24   973.90  1003.54   970.1100   976.22   1590328
1251   GOOG  2018-12-26   989.01  1040.00   983.0000  1039.46   2373270
1252   GOOG  2018-12-27  1017.15  1043.89   997.0000  1043.88   2109777
1253   GOOG  2018-12-28  1049.62  1055.56  1033.1000  1037.08   1413772
1254   GOOG  2018-12-31  1050.96  1052.70  1023.5900  1035.61   1493722

[1255 rows x 7 columns]

## 8.1.5 Supplementary Activity

### With the earthquakes.csv file, select all the earthquakes in Japan with a magType of mb and a magnitude of 4.9 or greater.

In [5]:
eq_jpn_greater_4_9 = earthquakes_df[(earthquakes_df['parsed_place']=='Japan') & (earthquakes_df['mag']>=4.9)]
eq_jpn_greater_4_9

,mag,magType,time,place,tsunami,parsed_place
476,5.2,mww,1539317747370,"7km ESE of Asahi, Japan",0,Japan
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
2591,5.0,mww,1538693073410,"144km E of Nago, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan
4409,5.0,mww,1538297644770,"33km NW of Shizunai, Japan",0,Japan
7832,5.3,mww,1537613881810,"169km E of Nago, Japan",0,Japan
9083,5.1,mww,1537287709100,"23km ENE of Ishinomaki, Japan",0,Japan

### Create bins for each full number of magnitude (for example, the first bin is 0-1, the second is 1-2, and so on) with a magType of ml and count how many are in each bin.

In [6]:
ml_df = earthquakes_df[earthquakes_df['magType'] == 'ml'].copy()

max_mag = int(np.ceil(ml_df['mag'].max()))
bins = np.arange(0, max_mag + 1, 1)
labels = [f"{i}-{i+1}" for i in range(0, max_mag)]

ml_df['mag_bin'] = pd.cut(
    ml_df['mag'],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

bin_counts = ml_df['mag_bin'].value_counts(sort=False)
bin_counts

mag_bin
0-1    2072
1-2    3126
2-3     985
3-4     153
4-5       6
5-6       2
Name: count, dtype: int64

### Using the faang.csv file, group by the ticker and resample to monthly frequency. Make the following aggregations:
- Mean of the opening price
- Maximum of the high price
- Minimum of the low price
- Mean of the closing price
- Sum of the volume traded

Mean of the opening price

In [7]:
mean_opening = faang_df.groupby('ticker', group_keys=True)[['open']].mean()
mean_opening

               open
ticker
AAPL     187.038674
AMZN    1644.072669
FB       171.454424
GOOG    1113.554104
NFLX     319.620533

Maximum of the high price

In [8]:
max_high = faang_df.groupby('ticker', group_keys=True)[['high']].max()
max_high

             high
ticker
AAPL     231.6645
AMZN    2050.5000
FB       218.6200
GOOG    1273.8900
NFLX     423.2056

Minimum of the low price

In [9]:
min_low = faang_df.groupby('ticker', group_keys=True)[['low']].min()
min_low

              low
ticker
AAPL     145.9639
AMZN    1170.5100
FB       123.0200
GOOG     970.1100
NFLX     195.4200

Mean of the closing price

In [10]:
mean_close = faang_df.groupby('ticker', group_keys=True)[['close']].mean()
mean_close

              close
ticker
AAPL     186.986218
AMZN    1641.726175
FB       171.510936
GOOG    1113.225139
NFLX     319.290299

Sum of the volume traded

In [11]:
sum_volume = faang_df.groupby('ticker', group_keys=True)[['volume']].sum()
sum_volume

            volume
ticker
AAPL    8539383858
AMZN    1418040266
FB      6949682394
GOOG     437403914
NFLX    2879045091

### Build a crosstab with the earthquake data between the tsunami column and the magType column. Rather than showing the frequency count, show the maximum magnitude that was observed for each combination. Put the magType along the columns.

In [12]:
eq_crosstab = earthquakes_df.groupby(['tsunami', 'magType'])[['mag']].max()
eq_crosstab

                  mag
tsunami magType
0       mb       5.60
        mb_lg    3.50
        md       4.11
        mh       1.10
        ml       4.20
        mw       3.83
        mwb      5.80
        mwr      4.80
        mww      6.00
1       mb       6.10
        ml       5.10
        ms_20    5.70
        mw       4.41
        mww      7.50

### Calculate the rolling 60-day aggregations of OHLC data by ticker for the FAANG data. Use the same aggregations as exercise no. 3.

In [13]:
# Filter stock data from first recorded day to 60 days later
faang_df['date'] = pd.to_datetime(faang_df['date'])
start_date = faang_df['date'].min()
end_date = start_date - pd.Timedelta(days=60)

In [14]:
faang_60d = faang_df[(faang_df['date'] > start_date) & (faang_df['date'] <= end_date)]

In [15]:
OHLC_60 = faang_df.groupby('ticker').agg(
    open_mean=('open', 'mean'),
    high_max=('high', 'max'),
    low_min=('low', 'min'),
    close_mean=('close', 'mean'),
    volume_sum=('volume', 'sum')
)
OHLC_60

          open_mean   high_max    low_min   close_mean  volume_sum
ticker
AAPL     187.038674   231.6645   145.9639   186.986218  8539383858
AMZN    1644.072669  2050.5000  1170.5100  1641.726175  1418040266
FB       171.454424   218.6200   123.0200   171.510936  6949682394
GOOG    1113.554104  1273.8900   970.1100  1113.225139   437403914
NFLX     319.620533   423.2056   195.4200   319.290299  2879045091

### Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [16]:
avg_OHLC_volume = faang_df.groupby('ticker').agg(
    open_mean=('open', 'mean'),
    high_mean=('high', 'mean'),
    low_mean=('low', 'mean'),
    close_mean=('close', 'mean'),
    volume_mean=('volume', 'mean')
)
avg_OHLC_volume

          open_mean    high_mean     low_mean   close_mean   volume_mean
ticker
AAPL     187.038674   188.906858   185.135729   186.986218  3.402145e+07
AMZN    1644.072669  1662.839801  1619.840398  1641.726175  5.649563e+06
FB       171.454424   173.615298   169.303110   171.510936  2.768798e+07
GOOG    1113.554104  1125.777649  1101.001594  1113.225139  1.742645e+06
NFLX     319.620533   325.224583   313.187273   319.290299  1.147030e+07

### Calculate the Z-scores for each numeric column of Netflix's data (ticker is NFLX) using apply().

In [17]:
# import zscore
from scipy.stats import zscore

In [18]:
netflix_stock_data = faang_df[faang_df['ticker']=='NFLX']

nflx_z_score = netflix_stock_data[['open', 'high', 'low', 'close', 'volume']].apply(zscore)
nflx_z_score

          open      high       low     close    volume
753  -2.505749 -2.521050 -2.415042 -2.421473 -0.088937
754  -2.385047 -2.428022 -2.290360 -2.339951 -0.508620
755  -2.300860 -2.410885 -2.239081 -2.328071 -0.961204
756  -2.279559 -2.350294 -2.206487 -2.238767 -0.783894
757  -2.223367 -2.299699 -2.148042 -2.196572 -1.040606
...        ...       ...       ...       ...       ...
999  -1.574618 -1.521399 -1.630448 -1.749435 -0.339680
1000 -1.738529 -1.442855 -1.680690 -1.344082  0.518073
1001 -1.410097 -1.420618 -1.498794 -1.305267  0.135138
1002 -1.251257 -1.291594 -1.299877 -1.294718 -0.085334
1003 -1.206222 -1.124597 -1.090706 -1.057529  0.360163

[251 rows x 5 columns]

### Add event descriptions:
- Create a dataframe with the following three columns: ticker, date, and event. The columns should have the following values:
    - ticker: 'FB'
    - date: ['2018-07-25', '2018-03-19', '2018-03-20']
    - event: ['Disappointing user growth announced after close.', 'Cambridge Analytica story', 'FTC investigation']
- Set the index to ['date', 'ticker']
- Merge this data with the FAANG data using an outer join

In [30]:
# Create FB DataFrame
data = {
    'ticker': ['FB', 'FB', 'FB'],
    'date': ['2018-07-25', '2018-03-19', '2018-03-20'],
    'event': ['Disappointing user growth announced after close.', 'Cambridge Analytica story', 'FTC investigation']
}

fb_df = pd.DataFrame(data).set_index(['date', 'ticker'])
fb_df

                                                              event
date       ticker
2018-07-25 FB      Disappointing user growth announced after close.
2018-03-19 FB                             Cambridge Analytica story
2018-03-20 FB                                     FTC investigation

In [34]:
# Outer join with faang_df
faang_df_merged = pd.merge(faang_df, fb_df, on='ticker', how='outer')
print(faang_df_merged[faang_df_merged['ticker']=='FB'])

     ticker       date    open    high     low   close    volume  \
502      FB 2018-01-02  177.68  181.58  177.55  181.42  18151903
503      FB 2018-01-02  177.68  181.58  177.55  181.42  18151903
504      FB 2018-01-02  177.68  181.58  177.55  181.42  18151903
505      FB 2018-01-03  181.88  184.78  181.33  184.67  16886563
506      FB 2018-01-03  181.88  184.78  181.33  184.67  16886563
...     ...        ...     ...     ...     ...     ...       ...
1250     FB 2018-12-28  135.34  135.92  132.20  133.20  22627569
1251     FB 2018-12-28  135.34  135.92  132.20  133.20  22627569
1252     FB 2018-12-31  134.45  134.64  129.95  131.09  24625308
1253     FB 2018-12-31  134.45  134.64  129.95  131.09  24625308
1254     FB 2018-12-31  134.45  134.64  129.95  131.09  24625308

                                                 event
502   Disappointing user growth announced after close.
503                          Cambridge Analytica story
504                                  FTC investigation
505   Disappointing user growth announced after close.
506                          Cambridge Analytica story
...                                                ...
1250                         Cambridge Analytica story
1251                                 FTC investigation
1252  Disappointing user growth announced after close.
1253                         Cambridge Analytica story
1254                                 FTC investigation

[753 rows x 8 columns]

### Use the transform() method on the FAANG data to represent all the values in terms of the first date in the data. To do so, divide all the values for each ticker by the values for the first date in the data for that ticker. This is referred to as an index, and the data for the first date is the base (https://ec.europa.eu/eurostat/statistics-explained/ index.php/ Beginners:Statisticalconcept-Indexandbaseyear). When data is in this format, we can easily see growth over time. Hint: transform() can take a function name.

In [ ]:
faang_index = faang_df.copy()
faang_index['date'] = pd.to_datetime(faang_index['date'])
faang_index = faang_index.sort_values(['ticker', 'date'])

value_cols = ['open', 'high', 'low', 'close', 'volume']
base_values = faang_index.groupby('ticker')[value_cols].transform('first')
faang_index[value_cols] = faang_index[value_cols].div(base_values)

faang_index.groupby('ticker').head(1)

     ticker       date  open  high  low  close  volume
251    AAPL 2018-01-02   1.0   1.0  1.0    1.0     1.0
502    AMZN 2018-01-02   1.0   1.0  1.0    1.0     1.0
0        FB 2018-01-02   1.0   1.0  1.0    1.0     1.0
1004   GOOG 2018-01-02   1.0   1.0  1.0    1.0     1.0
753    NFLX 2018-01-02   1.0   1.0  1.0    1.0     1.0

## Conclusion

The activity mainly tackles the aggregation of data in DataFrames. Specifically, I learned how to demonstrate querying and merging of DataFrames, perform calculations on to all data rows in DataFrames, aggregate DataFrames using pandas and numpy, and work with time series data. One of the commands often used in aggregating data is the groupby() method, which is used to group data based on one or more columns and perform aggregate functions on the grouped data. This method is particularly useful for summarizing and analyzing data in a structured way. I also used the apply() method, which can be used for standardizing data and identifying outliers. Overall, this activity has enhanced my understanding of how to manipulate and analyze data using pandas, which is a powerful tool for data analysis in Python.

# End