In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Extraction

In [2]:
df = pd.read_csv('urban_vs_environment_2.csv')
df.head()

,Indicator,Economy,Unit of Measure,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Definition,Data Coverage,Calendar Year,Base Year,Source,Footnotes
0,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Brunei Darussalam,micrograms per cubic meter,7.78476,6.89405,6.58513,6.76132,...,...,...,...,...,...,The mean annual concentration of fine suspende...,From 2016 to 2025,NaN,NaN,World Health Organization,NaN
1,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Cambodia,micrograms per cubic meter,19.70746,17.39564,17.72861,18.34848,...,...,...,...,...,...,The mean annual concentration of fine suspende...,From 2016 to 2025,NaN,NaN,World Health Organization,NaN
2,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Indonesia,micrograms per cubic meter,21.71451,19.10192,19.10978,19.93081,...,...,...,...,...,...,The mean annual concentration of fine suspende...,From 2016 to 2025,NaN,NaN,World Health Organization,NaN
3,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Lao People's Democratic Republic,micrograms per cubic meter,26.23168,22.64164,22.73672,24.18547,...,...,...,...,...,...,The mean annual concentration of fine suspende...,From 2016 to 2025,NaN,NaN,World Health Organization,NaN
4,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Malaysia,micrograms per cubic meter,25.27105,22.48911,22.60588,23.74462,...,...,...,...,...,...,The mean annual concentration of fine suspende...,From 2016 to 2025,NaN,NaN,World Health Organization,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Indicator        99 non-null     str
 1   Economy          99 non-null     str
 2   Unit of Measure  98 non-null     str
 3   2016             99 non-null     str
 4   2017             99 non-null     str
 5   2018             99 non-null     str
 6   2019             99 non-null     str
 7   2020             99 non-null     str
 8   2021             99 non-null     str
 9   2022             99 non-null     str
 10  2023             99 non-null     str
 11  2024             99 non-null     str
 12  2025             99 non-null     str
 13  Definition       88 non-null     str
 14  Data Coverage    98 non-null     str
 15  Calendar Year    37 non-null     str
 16  Base Year        0 non-null      float64
 17  Source           98 non-null     str
 18  Footnotes        28 non-null     str
dtypes: float64(1), str(18)
memory usage: 14.8 KB

# Transform

In [4]:
# Create copy of df
urbanization_df = df.copy()

In [5]:
# Drop unnecessary columns
cols_to_drop = ['Unit of Measure','Definition','Data Coverage','Calendar Year','Base Year','Source','Footnotes']
urbanization_df.drop(columns=cols_to_drop, inplace=True)
urbanization_df.head()

,Indicator,Economy,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Brunei Darussalam,7.78476,6.89405,6.58513,6.76132,...,...,...,...,...,...
1,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Cambodia,19.70746,17.39564,17.72861,18.34848,...,...,...,...,...,...
2,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Indonesia,21.71451,19.10192,19.10978,19.93081,...,...,...,...,...,...
3,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Lao People's Democratic Republic,26.23168,22.64164,22.73672,24.18547,...,...,...,...,...,...
4,Annual Mean Levels (Î¼g/mÂ³) of Fine Particula...,Malaysia,25.27105,22.48911,22.60588,23.74462,...,...,...,...,...,...

In [6]:
# Create indicator codes
urbanization_df['Indicator'].unique()

<StringArray>
['Annual Mean Levels (Î¼g/mÂ³) of Fine Particulate Matter (e.g., PM2.5 and PM10) in Cities (population weighted), Urban',
                                   'Fossil-fuel subsidies (consumption and production) as a proportion of total GDP (%)',
                                                                              'Urban population (% of total population)',
                                                                'Total Greenhouse Gas Emissions (t '000 CO₂ equivalent)',
                      'Temperature change with respect to a baseline climatology, corresponding to the period 1951-1980',
                                                                                 'Deforestation Rate (average % change)',
                                                                                            'Growth Rates in Population',
                                                                      'Carbon Dioxide Emissions (t '000 CO₂ equivalent)',
                                                                                                    'Population density']
Length: 9, dtype: str

In [7]:
# Create indicator codes dictionary
indicator_codes_dict = {
    "Annual Mean Levels (μg/m³) of Fine Particulate Matter (e.g., PM2.5 and PM10) in Cities (population weighted), Urban": "Urban Fine Particulate Matter Levels",
    "Annual Mean Levels (Î¼g/mÂ³) of Fine Particulate Matter (e.g., PM2.5 and PM10) in Cities (population weighted), Urban": "Urban Fine Particulate Matter Levels",
    "Fossil-fuel subsidies (consumption and production) as a proportion of total GDP (%)": "Fossil-fuel Subsidies and GDP Proportion",
    "Urban population (% of total population)": "Urban Population",
    "Total Greenhouse Gas Emissions (t '000 CO₂ equivalent)": "Total Greenhouse Gas Emissions",
    "Temperature change with respect to a baseline climatology, corresponding to the period 1951-1980": "Temperature Change",
    "Deforestation Rate (average % change)": "Deforestation Rate",
    "Growth Rates in Population": "Growth Rates in Population",
    "Carbon Dioxide Emissions (t '000 CO₂ equivalent)": "Carbon Dioxide Emissions",
    "Population density": "Population Density"
}
# Rename values in the Indicator column; keep original if not in dictionary
urbanization_df["Indicator"] = urbanization_df["Indicator"].map(indicator_codes_dict).fillna(urbanization_df["Indicator"])
urbanization_df['Indicator'].unique()

<StringArray>
[    'Urban Fine Particulate Matter Levels',
 'Fossil-fuel Subsidies and GDP Proportion',
                         'Urban Population',
           'Total Greenhouse Gas Emissions',
                       'Temperature Change',
                       'Deforestation Rate',
               'Growth Rates in Population',
                 'Carbon Dioxide Emissions',
                       'Population Density']
Length: 9, dtype: str

In [8]:
# Round off year column values to 2 decimal places
year_cols = [col for col in urbanization_df.columns if str(col).isdigit() and 2010 <= int(col) <= 2025]
urbanization_df[year_cols] = urbanization_df[year_cols].apply(pd.to_numeric, errors='coerce').round(2)

In [9]:
# Fill NaN values with 0 for year columns
urbanization_df[year_cols] = urbanization_df[year_cols].fillna(0)
urbanization_df.head()

,Indicator,Economy,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Urban Fine Particulate Matter Levels,Brunei Darussalam,7.78,6.89,6.59,6.76,0.0,0.0,0.0,0.0,0.0,0.0
1,Urban Fine Particulate Matter Levels,Cambodia,19.71,17.40,17.73,18.35,0.0,0.0,0.0,0.0,0.0,0.0
2,Urban Fine Particulate Matter Levels,Indonesia,21.71,19.10,19.11,19.93,0.0,0.0,0.0,0.0,0.0,0.0
3,Urban Fine Particulate Matter Levels,Lao People's Democratic Republic,26.23,22.64,22.74,24.19,0.0,0.0,0.0,0.0,0.0,0.0
4,Urban Fine Particulate Matter Levels,Malaysia,25.27,22.49,22.61,23.74,0.0,0.0,0.0,0.0,0.0,0.0

# Transformed DataFrame

In [10]:
urbanization_df

,Indicator,Economy,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Urban Fine Particulate Matter Levels,Brunei Darussalam,7.78,6.89,6.59,6.76,0.00,0.00,0.00,0.00,0.00,0.0
1,Urban Fine Particulate Matter Levels,Cambodia,19.71,17.40,17.73,18.35,0.00,0.00,0.00,0.00,0.00,0.0
2,Urban Fine Particulate Matter Levels,Indonesia,21.71,19.10,19.11,19.93,0.00,0.00,0.00,0.00,0.00,0.0
3,Urban Fine Particulate Matter Levels,Lao People's Democratic Republic,26.23,22.64,22.74,24.19,0.00,0.00,0.00,0.00,0.00,0.0
4,Urban Fine Particulate Matter Levels,Malaysia,25.27,22.49,22.61,23.74,0.00,0.00,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
94,Population Density,Philippines,341.77,347.23,352.52,357.67,362.67,367.33,371.91,376.31,376.00,0.0
95,Population Density,Singapore,7797.00,7796.00,7804.00,7866.00,7810.00,7485.00,7688.00,8058.00,8207.00,0.0
96,Population Density,Thailand,133.00,134.25,134.68,135.09,135.46,135.81,136.13,136.50,136.84,0.0
97,Population Density,Timor-Leste,81.91,83.16,84.40,85.65,86.96,88.36,89.66,91.01,93.69,0.0
98,Population Density,Viet Nam,281.53,284.65,287.97,290.83,295.00,297.39,300.00,302.75,305.86,0.0

In [11]:
# Save as CSV
urbanization_df.to_csv('urbanization_clean.csv', index=False)